### ISSUE TITLE
Latest update resulted in all newsfeed items displaying as unread

### ISSUE THREAD

**Issue by Minoru** [ForNeVeR/fornever.me#3]
I'm using newsbeuter in conjunction with TT-RSS and I've been subscribed to your blog ever since your ICFPC post, so my newsreader have seen your earlier posts and shouldn't have displayed them. But it did, so something must've changed. Do you have any insights?

**Comment by ForNeVeR** [comment]
I'm sorry about that. It seems that I've changed the GUIDs of all RSS items (added `https` instead of `http`). Next time I will be more careful with these thingies.
