### ISSUE TITLE
Support HEAD method

### ISSUE THREAD

**Issue by Minoru** [ForNeVeR/fornever.me#37]
When I send HEAD request to fornever.me, for example, with `curl -I https://fornever.me`, I get 405 Method Not Allowed with a header saying that I should only use GET. (Pardon me for the absence of a quote—I didn't save one and fornever.me is down at the moment.)

Expected behaviour is the server returning just the headers that I would normally get if I issue GET request. The point of the method is to save traffic when I'm only interested in the headers and not the body of the response.

**Comment by ForNeVeR** [comment]
I think that's a problem of my server implementation, I will fix that. Thanks for the report.

**Comment by ForNeVeR** [comment]
Fixed!
